Member card changes color based on undergjeng
Studentersamfundets-Interne-Teater/sit-web pull request #39
Opened 2021-01-10 19:19 UTC by livejac

2021-01-10 20:26 UTC, jakobsen commented
Kult!

Støtter at vi implementerer dette på siden, men mistenker at Javascript ikke er den beste måten å gjøre det på. Jeg tror det er et bedre alternativ å gjøre det ved Django-templaten. Da sender vi siden slik den skal se ut til klienten, og det er også mer robust om vi gjør endringer i hvordan medlemskortene ser ut eller hva som står på dem.

Det kunne f.eks. gjøres ved noe slikt som
```django
{% for medlem in mliste %}
  <a class="card card-{{medlem.get_undergjeng_display}}" href="{% url 'medlem_info' medlem.id %}">
  ...
{% endfor %}
```
eller lignende, og så sette rett bakgrunnsfarge i CSS.

2021-01-11 21:33 UTC, jacobwulffwold commented
Kan nevne at noen medlemmer ikke har undergjeng, så går an å ha disse i en egen farge også? For ikke-SITere stort sett

2021-01-12 15:20 UTC, livejac commented
Lurt @jakobsen. Endrer til det :)

Setter opp en default fallback for alle uten gruppering, @jacobwulffwold

2021-01-12 15:55 UTC, livejac commented
Da skal den være klar for review, igjen

2021-01-12 15:57 UTC, livejac commented
Tar endringer i wrapperen i en egen PR. Må flikke litt mer på den

2021-01-28 19:46 UTC, jakobsen requested changes
Denne ser jevnt over solid ut! Så din egen kommentar til at det er litt hårete med store variabler i CSS, så jeg la inn et forslag til hvordan det kan fikses direkte i Django-templaten. Om du synes det ser OK ut er det bare å commite endringen, så setter jeg denne til godkjent :)

2021-01-28 19:46 UTC, jakobsen commented on SITnett/graphics/style.css
> +.card-Kostyme{
Dette kan fikses gjennom en innebygget template tag i Django, se under.
```suggestion
.card-kostyme{
```

2021-01-28 19:46 UTC, jakobsen commented on SITnett/graphics/style.css
> +.card-Kulisse{
```suggestion
.card-kulisse{
```

2021-01-28 19:46 UTC, jakobsen commented on SITnett/graphics/style.css
> +.card-Skuespill{
```suggestion
.card-skuespill{
```

2021-01-28 19:46 UTC, jakobsen commented on SITnett/templates/medlemmer/medlemmer.html
> +		<a class="card card-{{medlem.get_undergjeng_display}}" href="{% url 'medlem_info' medlem.id %}">
Dette gjør strengen til lowercase:
```suggestion
		<a class="card card-{{ medlem.get_undergjeng_display|lower }}" href="{% url 'medlem_info' medlem.id %}">
```

2021-01-31 11:08 UTC, merged